### ISSUE TITLE
app is not rendering

### ISSUE THREAD

**Issue by dmcglinn** [sarahwie/refugee_migration_trends#3]
Hey @sarahwie I can't seem to get your app to render. I think there are two problems that I can identify. One was requiring that you use the structure of keeping all your scripts in the ./scripts directory. You should definitely move the files `server.R` and `ui.R` into the main directory. After making that change I get this error:

```
Object length mismatch:
     wrd_sp has 184 Polygons objects, but counts_by_country has 235 rows
```

**Comment by sarahwie** [comment]
Sorry for the delay. I'm going to look at it now and see what's up. This is the final version of my code which was working on my machine, but I did change the location of the scripts to meet the setup criteria for the github repository which I should have specified.

**Comment by sarahwie** [comment]
@dmcglinn I fixed the file structure and made sure the code was up-to-date with the final version on my computer, but once I completely clear my workspace and run it from scratch, everything works fine. I can't figure out why you're getting that error. The only thing I can think of is maybe the versions of the maps or sp package you're using is not the same as me and therefore the world map has fewer spatial polygons in it? I updated the Readme to include the package versions I'm using.

**Comment by dmcglinn** [comment]
Hey @sarahwie it looks like it is working better but there still is one issue. Take a look at the app here: 

http://uniola.biology.cofc.edu:3232/refugee_migration_trends/

When attempting to generate Migration Trends Over Time the following error occurs: 
`Warning: Error in getCountryTrends: object 'input' not found`

**Comment by sarahwie** [comment]
That should be fixed now.

**Comment by sarahwie** [comment]
Thanks for hosting it on the server!

**Comment by dmcglinn** [comment]
No problem. Thanks for your changes. I'm closing this but submitting a new bug report.
